# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(836, 506)
        Window.setStyleSheet("background-color: rgb(106, 106, 106);")
        self.gridLayout = QtWidgets.QGridLayout(Window)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Window)
        self.label.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(136, 136, 136);\n"
                                 "color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.dir_edit = QtWidgets.QLineEdit(Window)
        self.dir_edit.setMinimumSize(QtCore.QSize(0, 30))
        self.dir_edit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.dir_edit.setStyleSheet("background-color: rgb(200, 200, 200);\n"
                                    "")
        self.dir_edit.setObjectName("dir_edit")
        self.gridLayout.addWidget(self.dir_edit, 1, 0, 1, 2)
        self.load_files_button = QtWidgets.QPushButton(Window)
        self.load_files_button.setMinimumSize(QtCore.QSize(0, 30))
        self.load_files_button.setMaximumSize(QtCore.QSize(16777215, 30))
        self.load_files_button.setStyleSheet(
            "background-color: rgb(216, 216, 216);")
        self.load_files_button.setObjectName("load_files_button")
        self.gridLayout.addWidget(self.load_files_button, 1, 2, 1, 1)
        self.splitter = QtWidgets.QSplitter(Window)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(136, 136, 136);\n"
                                   "color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.src_files_list = QtWidgets.QListWidget(self.widget)
        self.src_files_list.setStyleSheet(
            "background-color: rgb(191, 191, 191);")
        self.src_files_list.setObjectName("src_files_list")
        self.verticalLayout.addWidget(self.src_files_list)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(136, 136, 136);\n"
                                   "color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.dst_files_list = QtWidgets.QListWidget(self.widget1)
        self.dst_files_list.setStyleSheet(
            "background-color: rgb(191, 191, 191);")
        self.dst_files_list.setObjectName("dst_files_list")
        self.verticalLayout_2.addWidget(self.dst_files_list)
        self.gridLayout.addWidget(self.splitter, 2, 0, 1, 3)
        self.label_4 = QtWidgets.QLabel(Window)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(136, 136, 136);\n"
                                   "color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 3)
        self.prefix_edit = QtWidgets.QLineEdit(Window)
        self.prefix_edit.setMinimumSize(QtCore.QSize(0, 30))
        self.prefix_edit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.prefix_edit.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.prefix_edit.setObjectName("prefix_edit")
        self.gridLayout.addWidget(self.prefix_edit, 4, 0, 1, 1)
        self.extension_label = QtWidgets.QLabel(Window)
        self.extension_label.setMinimumSize(QtCore.QSize(0, 30))
        self.extension_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.extension_label.setStyleSheet("background-color: rgb(136, 136, 136);\n"
                                           "color: rgb(255, 255, 255);")
        self.extension_label.setObjectName("extension_label")
        self.gridLayout.addWidget(self.extension_label, 4, 1, 1, 1)
        self.rename_files_button = QtWidgets.QPushButton(Window)
        self.rename_files_button.setMinimumSize(QtCore.QSize(0, 30))
        self.rename_files_button.setMaximumSize(QtCore.QSize(16777215, 30))
        self.rename_files_button.setStyleSheet(
            "background-color: rgb(216, 216, 216);")
        self.rename_files_button.setObjectName("rename_files_button")
        self.gridLayout.addWidget(self.rename_files_button, 4, 2, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(Window)
        self.progressBar.setStyleSheet("color: rgb(255, 255, 255);\n"
                                       "gridline-color: rgb(255, 85, 127);")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 5, 0, 1, 3)

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "RP Renamer"))
        self.label.setText(_translate("Window", "Last Source Directory:"))
        self.load_files_button.setText(_translate("Window", "&Load Files"))
        self.label_2.setText(_translate("Window", "Files to Rename"))
        self.label_3.setText(_translate("Window", "Renamed Files"))
        self.label_4.setText(_translate("Window", "Filename Prefix:"))
        self.prefix_edit.setPlaceholderText(_translate(
            "Window", "What do you want to rename your files to?"))
        self.extension_label.setText(_translate("Window", "*.jpg"))
        self.rename_files_button.setText(_translate("Window", "&Rename"))
